/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "shelstring.check" instead.
 */

#include <check.h>

#line 1 "shelstring.check"
#include "shelstring.h"

#define LEN 8

START_TEST(shelint_length_from_cint_check)
{
#line 6
int tests[LEN] = {0, 1, 5, 127,128,255,16383,16384};
short res[LEN] = {1, 1, 1,   1,  2,  2,    2,    3};
for(int i=0;i<LEN;i++){
  ck_assert_int_eq(res[i],shelint_length_from_cint(tests[i]));
 }

}
END_TEST

START_TEST(general_runthrough)
{
#line 13
char* test_cstring = "The quick brown fox jumped over the lazy dog";
char test_binary_data[45] = "Test\0OhSHIT A NULL WHAT ARE WE TO DO\x00blarg";
shelstring test_shelstr = cstring_to_shelstring(test_cstring);
ck_assert_uint_eq(shelstrlen(test_shelstr),strlen(test_cstring));
shelstring binary_shelstr = chars_to_shelstring(test_binary_data,45);
ck_assert_uint_eq(shelstrlen(binary_shelstr),45);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, shelint_length_from_cint_check);
    tcase_add_test(tc1_1, general_runthrough);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
